
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: svrfarms_development


test:
  <<: *default
  database: svrfarms_test

production:
  <<: *default
  database: svrfarms_production
  username: svrfarms
  password: <%= ENV['SVRFARMS_DATABASE_PASSWORD'] %>
